// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Jo6Y_W9hZDdzcdNSYfAQt21ndfn1o10',
    appId: '1:263085515409:android:dc70b0f4bf43ed68405530',
    messagingSenderId: '263085515409',
    projectId: 'seelai-3d7ff',
    storageBucket: 'seelai-3d7ff.firebasestorage.app',
    databaseURL: 'https://seelai-3d7ff-default-rtdb.firebaseio.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11ECRZ4_fY07AuEz1sycZ1RWMYzwdaVw',
    appId: '1:263085515409:ios:ffd9ca64db3238d2405530',
    messagingSenderId: '263085515409',
    projectId: 'seelai-3d7ff',
    storageBucket: 'seelai-3d7ff.firebasestorage.app',
    iosBundleId: 'com.example.seelai',
    databaseURL: 'https://seelai-3d7ff-default-rtdb.firebaseio.com',

  );

}